### ISSUE TITLE
Wrong position of popper element with position:fixed & html/body height: 100%

### ISSUE THREAD

**Issue by sychevyi** [FezVrasta/popper.js#302]
### CodePen demo

Bad: https://codepen.io/anon/pen/jwPXXq
Without height: https://codepen.io/anon/pen/qjdLwK
Good: https://codepen.io/anon/pen/mwJavg

### Steps to reproduce the problem

1.  Open 'bad' example, scroll content. Popper moves away from reference
2.  Open 'without height' example, scroll content. Popper stays with reference
3.  Open 'good' example, scroll content. Popper stays with reference, as boundariesElement set to 'viewport'

### What is the expected behavior?

Popper stays with reference, without additional settings (?)

### What went wrong?

If html & body are styled with 'height: 100%', content is scrolled and reference is inside 'position: fixed' container, popper moves away from reference.

### Any other comments?

Actually I've found workaround (see 'good' example), just wanted to check if it's a bug or expected behavior.
Thanks for your time!

BTW, thanks for the 'popper-enabled' branch of the 'react-select', works good for me!

**Comment by nblackburn** [comment]
This seems to have been introduced in one of the more recent releases.

**Comment by FezVrasta** [comment]
Looks like [1.9.4](https://github.com/FezVrasta/popper.js/releases/tag/v1.9.4) broken it

**Comment by hekigan** [comment]
Same issue, and as @FezVrasta wrote, if I rollback to v1.9.3, the problem disappears.
In 1.10.8, the problem is still present.

**Comment by arvinsingla** [comment]
I'm also encountering this when using react-popper in our react app. I only have `height: 100%` on body. Unfortunately the workaround used by @sychevyi doesn't suit our UX as I need the popper attached to the scrollParent.

**Comment by okize** [comment]
I'm seeing this issue with `height: 100vh` on body as well. These body height settings are a common technique used to achieve a "sticky" footer.

**Comment by FezVrasta** [comment]
May someone conform it works fine on Safari Mobile? I'm from iPhone now and I see it correctly

**Comment by okize** [comment]
@FezVrasta looking on my iPhone, the good and bad CodePen examples @sychevyi posted look identical. On desktop (Chrome/Mac) the "bad" example has a popover that drifts away from it's ref as you scroll the content.

**Comment by Johann-S** [comment]
Is it a good solution to set : `boundariesElement: 'viewport'` to fix this issue ? 
Because if it's the case we should allow to change boudariesElement in Bootstrap Tooltips 🤔

**Comment by FezVrasta** [comment]
Nope this is a situation popper should handle by default.

**Comment by pascalduez** [comment]
Hi,

same issue here, as soon a a parent has a `heigh: 100%` the positioning becomes a bit crazy. 
Especially if the popper is rather at the bottom of the parent/page.

**Comment by skunkbad** [comment]
Now that bootstrap v4 beta is released, and tooltips are now handled by popper.js instead of tether, I think this issue is happening to  me. Maybe somebody here can confirm:

[https://codepen.io/skunkbad/pen/prrOWR](https://codepen.io/skunkbad/pen/prrOWR )

**Comment by pascalduez** [comment]
@skunkbad confirmed, looks similar.

**Comment by DaleMckeown** [comment]
@FezVrasta Just so you know, this bug is still here in 1.12.2.

https://www.codeply.com/go/HcvuTaMZPu

**Comment by FezVrasta** [comment]
Yes that's why the issue is still open 😉

**Comment by Jossnaz** [comment]
what is the recommended work around? if there is any I mean... fall back to 1.9.3? does that work with bootstrap 4 beta?

**Comment by tpetry** [comment]
1.9.3 works with bootstrap 4-beta, have been using it since weeks.

**Comment by Johann-S** [comment]
With the release of the first Bootstrap 4 beta we recommend to use Popper.js >= 1.11.0

**Comment by FezVrasta** [comment]
Hey guys, please review this PR https://github.com/FezVrasta/popper.js/pull/394

**Comment by FezVrasta** [comment]
I reviewed the various repros linked in this issue, the only one that didn't get fixed by 1.12.3 is this one:
https://github.com/FezVrasta/popper.js/issues/302#issuecomment-322022418

I think this problem is related to #331

**Comment by FezVrasta** [comment]
1.12.5 re-fixed it, sorry for the inconvenience.

**Comment by mycarrysun** [comment]
Something I was unaware of (and can't find in the docs) is that the popper needs to be outside any elements with abnormal positioning. 

I had padding inside the element that the popper was located in (think sidebar padding) and it was pushing the popper off the screen the same amount as the sidebar width. Moving it to the root (outside the element with the padding for the sidebar) fixed the positioning of the popper.

**Comment by FezVrasta** [comment]
@mycarrysun this shouldn't be the case, please open an issue if you can manage to reduce the problem to a basic code-pen example

**Comment by abhishek-apty** [comment]
I still see this issue in 2.11.5.
The html height is 100% and there is a fixed header with some px. Now if I point the popper to an element in the body, it is moved away from the reference with the same height of fixed header.
@FezVrasta Can you let me know if I am missing anything.

**Comment by FezVrasta** [comment]
Are you able to test it with Floating UI to see if it's been fixed there already?

**Comment by abhishek-apty** [comment]
I am using @popperjs/core. Didn't try with Floating UI. Let me check there and update.

**Comment by abhishek-apty** [comment]
Hi @FezVrasta, I see there are many changes in floating UI. So, updating all of that in my code base would take some time. Do you have any suggestion in mind using popperJS

**Comment by abhishek-apty** [comment]
Just checked with a sample code and Floating UI works fine. Do you have anything in mind to fix popperJS?

**Comment by atomiks** [comment]
Might be fixed in Popper if you disable `adaptive` option  in `computeStyles`

**Comment by abhishek-apty** [comment]
That solved my issue @atomiks. Thanks for the quick solution. Will I see any other issues, if I disable adaptive property?
